name: claimd_task
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_serializable: ^6.2.0
  dio: ^4.0.6
  url_launcher: ^6.1.5
  provider: ^6.0.3
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter:

  uses-material-design: true

  assets:
    - assets/images/exchangeagram.png
    - assets/images/intern.jpeg
    - assets/images/hero.jpeg
    - assets/images/group.jpeg

  fonts:
    - family: Vegan
      fonts:
       - asset: assets/fonts/Vegan-Style.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
    - family: IbarraRealNova
      fonts:
        - asset: assets/fonts/IbarraRealNova-Regular.ttf
        - asset: assets/fonts/IbarraRealNova-Bold.ttf
          weight: 700
        - asset: assets/fonts/IbarraRealNova-Italic.ttf
          style: italic

